spring.application.name=sistema-hospedagem

# CONFIGURAÇÃO DO BANCO MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_hospedagem?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Sao_Paulo
spring.datasource.username=root
spring.datasource.password=123456

# DRIVER MYSQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# PORTA DO SERVIDOR
server.port=8080

# UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true